### ISSUE TITLE
the memory management of fragments in viewpager2

### ISSUE THREAD

**Issue by AndyGu** [googlesamples/android-viewpager2#3]
The scenes I met is that when I store fragments in viewpager2, then I switch them using ”setCurrentItem(position, false)“, there is no certain method called in Fragment's lifecycle, sometimes it calls onAttach() onCreate() and so on, sometimes no method is called(it is related to the memory management I guess). I know I can call registerOnPageChangeCallback of viewpager2, but what I faced is I may fail when I do something to the fragment that I setCurrentItem to, because the fragment will init again when the lifecycle methods called after the callback of onPageSelected.
So am I do the code wrong way or is there some certain method can be called in fragment when switching the fragments, or I can call some method to manage the memory of viewpager2?

**Comment by gielzak** [comment]
Hi, thanks for raising this. Could you file a bug on https://issuetracker.google.com/issues?q=componentid:561920

I think it might already be covered by: https://issuetracker.google.com/issues/124183800
If not, please open another bug.

I'm going to close the Issues section on GitHub, so we have one place to track bugs (issuetracker.google.com) and don't miss anything.
